### ISSUE TITLE
cbrother 脚本是否有开源的计划？

### ISSUE THREAD

**Issue by fenginsc** [CBrotherScript/tencentcloud-sdk-cb#1]
cbrother脚本语言是否有开源的计划？
支持国产语言

**Comment by CBrotherScript** [comment]
一门脚本语言要做大，开源是必须要做的事情，但是开源的前提是形成了开发者社区，应该是一个漫长的过程。因为国内环境，提前开源对于脚本的发展来说，弊大于利。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CBrotherScript/tencentcloud-sdk-cb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月20日(星期天) 下午3:38
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[CBrotherScript/tencentcloud-sdk-cb] cbrother 脚本是否有开源的计划？ (Issue #1)





 
cbrother脚本语言是否有开源的计划？
 支持国产语言
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fenginsc** [comment]
明白，国内开源环境确实不好，但您可以考虑使用GPL开源协议，避免版权纠纷。
最后希望您的语言越来越好
